### ISSUE TITLE
NetCDF 4?

### ISSUE THREAD

**Issue by bernd-wechner** [stcorp/pupynere#1]
I have a NetCDF file this won't read. And it's because the magic 3 bytes it's looking for at start of file which should read 'CDF' don't. In fact the first 4 bytes are '\x89HDF', suggesting to me it's probably a NetCDF 3 vs 4 thing with 4 having moved to HDF5 as internal format.

**Comment by svniemeijer** [comment]
First, this is not the official repository for pupynere. It is a fork of the old official repository (that now seems to be gone).

If you want to use netcdf4 then you shoud use https://pypi.org/project/netCDF4/
